### ISSUE TITLE
Add support for editing custom fields on the TemplateSignatureRequest

### ISSUE THREAD

**Issue by alexmac05** [HelloFax/hellosign-dotnet-sdk#29] opened 2016-10-20 17:17 UTC
CHANGE FROM:
 var request = new TemplateSignatureRequest();
 request.AddTemplate(template_withBasicCustomFields);
 request.Subject = "Template test";
 request.Message = "Template message";
 request.AddSigner("Client", "george@example.com", "George");
 request.AddCustomField("newline", "$20,000");
 request.TestMode = true;

CHANGE TO: 
Being able to support the parameters Editor and Required also in Adding CustomField

like this, which was created using RestSharp (because the SDK does not support currently editor and required:

request.AddParameter("custom_fields", "[{\"name\":\"newline\", \"value\":\"$20,000\", \"editor\":\"Client\", \"required\":true}]");

CHANGE AREAS:
https://github.com/HelloFax/hellosign-dotnet-sdk/blob/v3/HelloSign/HelloSign.cs#L603
https://github.com/HelloFax/hellosign-dotnet-sdk/blob/v3/HelloSign/HelloSign.cs#L1238

**Comment by jyoung488** [comment] 2019-01-09 19:29
closing - duplicate of #47

**Closed as completed by jyoung488** 2019-01-09 19:29 UTC
